tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BI_ADMIN
      database: tasty_bytes_dbt_db_CA
      schema: dev
      warehouse: PRD_BI_WH_XS
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: BI_ADMIN
      database: tasty_bytes_dbt_db_CA
      schema: prod
      warehouse: PRD_BI_WH_XS